---
#
# ===================================================================
# Run-time Config file
# ===================================================================
#

# Auth - just a placeholder for now
username: admin
password: guest
